[Settings]
ID = "https://jeglobalcouncil.netlify.com"

[[redirects]]
  from = "/api/*"
  to = "https://junior-connect.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Authorization = "JC_PLACEHOLDER"

[[redirects]]
  from = "/map"
  to = "/contact"
