# Instructions on https://www.netlifycms.org/docs/add-to-your-site/
# Or in video form: https://www.youtube.com/watch?v=_CNZJLYvINc

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "source/_posts/insights"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["name"], valueField: "name"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Category", name: "topic", widget: "select", options: ["People", "Sales", "Projects", "Network", "Enlargement"] }
      - {label: "Blog Post Content", name: "body", widget: "markdown"}

  - name: "authors"
    label: "Authors"
    folder: "source/_posts/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "author"}
      - {label: "Author Name", name: "author_name", widget: "string"}
      - {label: "Author Description", name: "description", widget: "string"}
      - {label: "Profile Image", name: "image", widget: "image"}

  - name: "media-publications"
    label: "Media Publications"
    folder: "source/_posts/media"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "media-publication"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Media Outlet", name: "outlet", widget: "string"}
      - {label: "Language of Publication", name: "language", widget: "string", default: "English"}
      - {label: "Link to Publication", name: "link", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Publish Date (Used for ordering)", name: "date", widget: "date"}

  - name: "partners"
    label: "Partners"
    folder: "source/_posts/partners"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "partner"}
      - {label: "Partner Name", name: "partner_name", widget: "string"}
      - {label: "Partner Description", name: "description", widget: "string"}
      - {label: "Premium Partner?", name: "premium", widget: "boolean", default: "false"}
      - {label: "Partner Logo", name: "logo", widget: "image"}
      - {label: "Partner Website", name: "link", widget: "string"}
