# Instructions on https://www.netlifycms.org/docs/add-to-your-site/
# Or in video form: https://www.youtube.com/watch?v=_CNZJLYvINc

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "source/_posts/insights"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["name"], valueField: "name"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Category", name: "topic", widget: "select", options: ["People", "Sales", "Projects", "Network", "Enlargement"] }
      - {label: "Blog Post Content", name: "body", widget: "markdown"}

  - name: "post-authors"
    label: "Post Authors"
    folder: "source/_posts/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "author"}
      - {label: "Author Name", name: "title", widget: "string"}
      - {label: "Author Description", name: "description", widget: "string"}
      - {label: "Profile Image", name: "image", widget: "image"}

  - name: "media-publications"
    label: "Media Publications"
    folder: "source/_posts/media"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "media-publication"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Media Outlet", name: "outlet", widget: "string"}
      - {label: "Language of Publication", name: "language", widget: "string", default: "English"}
      - {label: "Link to Publication", name: "link", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}

  - name: "gc-partners"
    label: "GC Partners"
    folder: "source/_posts/partners"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "partner"}
      - {label: "Partner Name", name: "title", widget: "string"}
      - {label: "Partner Description", name: "description", widget: "string"}
      - {label: "Premium Partner?", name: "premium", widget: "boolean", default: "false"}
      - {label: "Partner Logo", name: "logo", widget: "image"}
      - {label: "Partner Website", name: "link", widget: "string"}

  - name: "confederations"
    label: "GC Confederations"
    folder: "source/_posts/confederations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "confederation"}
      - {label: "Confederation Name", name: "title", widget: "string"}
      - {label: "Confederation Logo", name: "logo", widget: "image"}
      - {label: "Number of JEs", name: "no_of_JEs", widget: "number"}
      - {label: "Number of JEurs", name: "no_of_JEurs", widget: "number"}
      - {label: "Number of Projects Last Year", name: "no_of_projects", widget: "number"}
      - {label: "Turnover in Local Currency Last Year", name: "turnover", widget: "number"}
      - {label: "Conversion Rate of Local Currency to USD by the end of Last Year", name: "conversion_rate", widget: "number"}
      - {label: "Don't count twice? (Mark true if this confederation is part of another GC Confederation)", name: "skip", widget: "boolean", default: "false"}
      - {label: "Website URL", name: "full_url", widget: "string"}
      - {label: "Website URL (Pretty version, without http or /'s)", name: "short_url", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string"}
      - {label: "Instagram", name: "instagram", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}

  - name: "jade-members"
    label: "JADE Members"
    folder: "source/_posts/jade-members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "select", options: ["jade-member", "consultative-member"] }
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Number of JEs (Leave empty if Consultative Member)", name: "no_of_JEs", widget: "number"}
      - {label: "Website URL", name: "full_url", widget: "string"}
      - {label: "Website URL (Pretty version, without http or /'s)", name: "short_url", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string"}
      - {label: "Instagram", name: "instagram", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
